# Generated by Django 5.1.5 on 2025-01-31 18:33

import ckeditor.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question in English')),
                ('answer', ckeditor.fields.RichTextField(verbose_name='Answer in English')),
                ('question_hi', models.TextField(blank=True, null=True, verbose_name='Question in Hindi')),
                ('question_bn', models.TextField(blank=True, null=True, verbose_name='Question in Bengali')),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer in Hindi')),
                ('answer_bn', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer in Bengali')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]# Generated by Django 5.1.5 on 2025-01-31 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('question_hi', models.TextField(blank=True, null=True)),
                ('question_bn', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
